-- ============================================================================
-- THIS FILE IS GENERATED by scripts/bundle.sh from src/*.lua. DO NOT EDIT.
-- ============================================================================

-- ============================================================================
-- bundled: src/json.lua
-- ============================================================================
-- ============================================================================
-- c4/src/json.lua — minimal JSON encoder/decoder for Control4 (Lua 5.1 safe).
--
-- Bundling rule: this file defines the global JSON table only. No require,
-- no return, no top-level execution, no Lua 5.2+ features (no \x escapes,
-- no bitwise operators, no string.pack, no table.pack).
-- ============================================================================

JSON = JSON or {}

-- Sentinel for explicit JSON null in encoded output (Lua nil cannot occupy
-- an array slot). Decoded nulls still arrive as nil (absent key).
JSON.null = JSON.null or {}

local function is_array(t)
  local count = 0
  for k, _ in pairs(t) do
    if type(k) ~= "number" or k < 1 or math.floor(k) ~= k then
      return false
    end
    count = count + 1
  end
  if count == 0 then
    return true -- empty table encodes as []; our protocol never needs {}.
  end
  for i = 1, count do
    if t[i] == nil then
      return false
    end
  end
  return true
end

local escapes = {
  ['"'] = '\\"',
  ["\\"] = "\\\\",
  ["\008"] = "\\b",
  ["\012"] = "\\f",
  ["\n"] = "\\n",
  ["\r"] = "\\r",
  ["\t"] = "\\t",
}

function JSON.encode(value)
  if value == JSON.null then
    return "null"
  end
  local vtype = type(value)
  if vtype == "nil" then
    return "null"
  elseif vtype == "boolean" then
    return value and "true" or "false"
  elseif vtype == "number" then
    if value ~= value or value == math.huge or value == -math.huge then
      error("JSON cannot encode NaN or infinity")
    end
    return string.format("%.14g", value)
  elseif vtype == "string" then
    return '"'
      .. value:gsub('[%z\001-\031\\"]', function(ch)
        return escapes[ch] or string.format("\\u%04x", string.byte(ch))
      end)
      .. '"'
  elseif vtype == "table" then
    local parts = {}
    if is_array(value) then
      for i = 1, #value do
        parts[#parts + 1] = JSON.encode(value[i])
      end
      return "[" .. table.concat(parts, ",") .. "]"
    end
    for k, v in pairs(value) do
      if type(k) ~= "string" then
        error("JSON object keys must be strings")
      end
      parts[#parts + 1] = JSON.encode(k) .. ":" .. JSON.encode(v)
    end
    return "{" .. table.concat(parts, ",") .. "}"
  end
  error("JSON cannot encode type " .. vtype)
end

local function utf8_encode(code)
  if code < 128 then
    return string.char(code)
  elseif code < 2048 then
    return string.char(
      192 + math.floor(code / 64),
      128 + (code % 64)
    )
  elseif code < 65536 then
    return string.char(
      224 + math.floor(code / 4096),
      128 + (math.floor(code / 64) % 64),
      128 + (code % 64)
    )
  end
  return string.char(
    240 + math.floor(code / 262144),
    128 + (math.floor(code / 4096) % 64),
    128 + (math.floor(code / 64) % 64),
    128 + (code % 64)
  )
end

local function new_decoder(text)
  local pos = 1
  local len = #text
  local decode_value -- forward declaration for recursion

  local function fail(msg)
    error("JSON decode error at byte " .. pos .. ": " .. msg)
  end

  local function skip_ws()
    while pos <= len do
      local ch = text:sub(pos, pos)
      if ch == " " or ch == "\t" or ch == "\n" or ch == "\r" then
        pos = pos + 1
      else
        break
      end
    end
  end

  local function decode_string()
    -- pos is on the opening quote.
    pos = pos + 1
    local parts = {}
    while true do
      if pos > len then
        fail("unterminated string")
      end
      local ch = text:sub(pos, pos)
      if ch == '"' then
        pos = pos + 1
        return table.concat(parts)
      elseif ch == "\\" then
        local esc = text:sub(pos + 1, pos + 1)
        if esc == '"' or esc == "\\" or esc == "/" then
          parts[#parts + 1] = esc
          pos = pos + 2
        elseif esc == "b" then
          parts[#parts + 1] = "\008"
          pos = pos + 2
        elseif esc == "f" then
          parts[#parts + 1] = "\012"
          pos = pos + 2
        elseif esc == "n" then
          parts[#parts + 1] = "\n"
          pos = pos + 2
        elseif esc == "r" then
          parts[#parts + 1] = "\r"
          pos = pos + 2
        elseif esc == "t" then
          parts[#parts + 1] = "\t"
          pos = pos + 2
        elseif esc == "u" then
          local hex = text:sub(pos + 2, pos + 5)
          local code = tonumber(hex, 16)
          if code == nil then
            fail("bad \\u escape")
          end
          pos = pos + 6
          if code >= 55296 and code <= 56319 then
            -- High surrogate: expect a low surrogate next.
            if text:sub(pos, pos + 1) ~= "\\u" then
              fail("lone high surrogate")
            end
            local low = tonumber(text:sub(pos + 2, pos + 5), 16)
            if low == nil or low < 56320 or low > 57343 then
              fail("bad low surrogate")
            end
            pos = pos + 6
            code = 65536 + (code - 55296) * 1024 + (low - 56320)
          end
          parts[#parts + 1] = utf8_encode(code)
        else
          fail("bad escape \\" .. esc)
        end
      else
        parts[#parts + 1] = ch
        pos = pos + 1
      end
    end
  end

  local function decode_number()
    local numtext = text:match("^%-?%d+%.?%d*[eE]?[+-]?%d*", pos)
    if numtext == nil or numtext == "" or numtext == "-" then
      fail("bad number")
    end
    -- Reject malformed tails like "1e" or "1." that the pattern may accept.
    if numtext:match("[eE][+-]?$") or numtext:match("%.$") then
      fail("bad number")
    end
    pos = pos + #numtext
    local num = tonumber(numtext)
    if num == nil then
      fail("bad number")
    end
    return num
  end

  local function decode_array()
    -- pos is on '['.
    pos = pos + 1
    local arr = {}
    skip_ws()
    if text:sub(pos, pos) == "]" then
      pos = pos + 1
      return arr
    end
    while true do
      arr[#arr + 1] = decode_value()
      skip_ws()
      local ch = text:sub(pos, pos)
      if ch == "]" then
        pos = pos + 1
        return arr
      elseif ch ~= "," then
        fail("expected ',' or ']' in array")
      end
      pos = pos + 1
    end
  end

  local function decode_object()
    -- pos is on '{'.
    pos = pos + 1
    local obj = {}
    skip_ws()
    if text:sub(pos, pos) == "}" then
      pos = pos + 1
      return obj
    end
    while true do
      skip_ws()
      if text:sub(pos, pos) ~= '"' then
        fail("expected string key in object")
      end
      local key = decode_string()
      skip_ws()
      if text:sub(pos, pos) ~= ":" then
        fail("expected ':' in object")
      end
      pos = pos + 1
      obj[key] = decode_value()
      skip_ws()
      local ch = text:sub(pos, pos)
      if ch == "}" then
        pos = pos + 1
        return obj
      elseif ch ~= "," then
        fail("expected ',' or '}' in object")
      end
      pos = pos + 1
    end
  end

  decode_value = function()
    skip_ws()
    if pos > len then
      fail("unexpected end of input")
    end
    local ch = text:sub(pos, pos)
    if ch == "{" then
      return decode_object()
    elseif ch == "[" then
      return decode_array()
    elseif ch == '"' then
      return decode_string()
    elseif ch == "t" and text:sub(pos, pos + 3) == "true" then
      pos = pos + 4
      return true
    elseif ch == "f" and text:sub(pos, pos + 4) == "false" then
      pos = pos + 5
      return false
    elseif ch == "n" and text:sub(pos, pos + 3) == "null" then
      pos = pos + 4
      return nil
    elseif ch == "-" or (ch >= "0" and ch <= "9") then
      return decode_number()
    end
    fail("unexpected character '" .. ch .. "'")
  end

  return {
    run = function()
      local value = decode_value()
      skip_ws()
      if pos <= len then
        fail("trailing data")
      end
      return value
    end,
  }
end

function JSON.decode(text)
  if type(text) ~= "string" then
    error("JSON.decode expects a string")
  end
  return new_decoder(text).run()
end

-- ============================================================================
-- bundled: src/model.lua
-- ============================================================================
-- ============================================================================
-- c4/src/model.lua — FloLogic constants and valve/account decoding.
--
-- Pure logic ported from custom_components/flologic/{const,api}.py. Defines
-- the global FloModel table only. No require, no return, no top-level
-- execution, Lua 5.1 safe (no bitwise operators: flag tests use arithmetic).
-- ============================================================================

FloModel = FloModel or {}

-- Controllable valve modes: name -> cloud bit value.
FloModel.VALVE_MODES = { home = 1, away = 2, bypass = 4, shutoff = 8, disabled = 16 }
FloModel.MODE_NAMES = { [1] = "home", [2] = "away", [4] = "bypass", [8] = "shutoff", [16] = "disabled" }

FloModel.VALVE_MODE_FLAGS = {
  home = 1, away = 2, bypass = 4, shutoff = 8, disabled = 16,
  flow_time_exceeded = 32, external_leak = 64, auto_away = 128,
  external_bypass = 256, delay_away = 512, external_away = 1024,
  override = 2048, ac_lost = 4096, change_battery = 8192, error = 16384,
  sensor_leak = 32768, system_down = 65536, valve_failure = 131072,
  communication_error = 262144, external_home = 524288,
  external_emergency_shutdown = 1048576, updating = 2097152,
  external_override = 4194304, low_temp_alert = 8388608,
  low_temp_shutoff = 16777216, humidity_sensor_shutoff = 33554432,
  low_temp_sensor_shutoff = 67108864, unknown = 268435456,
}

local F = FloModel.VALVE_MODE_FLAGS
FloModel.MODE_FLAG_NAMES = {}
for name, bit in pairs(F) do
  FloModel.MODE_FLAG_NAMES[bit] = name
end

FloModel.WATER_OFF_MODE_FLAGS = {
  F.flow_time_exceeded, F.external_leak, F.sensor_leak, F.shutoff,
  F.external_emergency_shutdown, F.low_temp_shutoff,
  F.humidity_sensor_shutoff, F.low_temp_sensor_shutoff,
}
FloModel.WARNING_ALERT_MODE_FLAGS = {
  F.low_temp_alert, F.change_battery, F.ac_lost, F.communication_error, F.updating,
}
FloModel.CRITICAL_MODE_FLAGS = { F.error, F.system_down, F.valve_failure, F.unknown }

FloModel.MODE_STATUS_PRIORITY = {
  F.flow_time_exceeded, F.sensor_leak, F.external_leak,
  F.external_emergency_shutdown, F.low_temp_shutoff,
  F.humidity_sensor_shutoff, F.low_temp_sensor_shutoff, F.shutoff,
  F.delay_away, F.auto_away, F.external_away, F.away, F.external_bypass,
  F.bypass, F.external_home, F.home, F.disabled, F.updating,
  F.communication_error, F.valve_failure, F.system_down, F.error, F.unknown,
}

FloModel.FLOW_STATE_NAMES = { [1] = "No flow", [2] = "New flow", [4] = "Flow", [8] = "Valve closed" }

FloModel.NOTIFICATION_FLAGS = {
  always = 1, never = 2, mode_change = 4, auto_shutoff = 8, auto_away = 16,
  delay_away = 32, advance_shutoff = 64, guest_mode = 128,
  connection_change = 256, general_alert = 512, critical_error = 1024,
  no_flow = 2048,
}

-- Lua 5.1 has no bitwise operators: test a single power-of-two flag
-- arithmetically. All flag values used here are exact in doubles.
function FloModel.has_flag(value, flag)
  if value == nil or flag == nil or flag <= 0 then
    return false
  end
  return math.floor(value / flag) % 2 == 1
end

function FloModel.has_any_flag(value, flags)
  for _, flag in ipairs(flags) do
    if FloModel.has_flag(value, flag) then
      return true
    end
  end
  return false
end

local function to_number(value)
  if type(value) == "number" then
    return value
  end
  if type(value) == "string" then
    return tonumber(value)
  end
  return nil
end

function FloModel.unique_id_prefix(valve)
  local uuid = valve.uuid
  if uuid ~= nil and uuid ~= "" then
    return tostring(uuid)
  end
  return tostring(valve.id)
end

function FloModel.valve_name(valve)
  return valve.valveFriendlyName
    or valve.combinedName
    or valve.name
    or valve.uuid
    or "FloLogic"
end

function FloModel.mode_name(valve)
  local mode = to_number(valve.mode)
  if mode == nil then
    return nil
  end
  local exact = FloModel.MODE_NAMES[mode]
  if exact ~= nil then
    return exact
  end
  local modes = FloModel.VALVE_MODES
  if FloModel.has_any_flag(mode, FloModel.WATER_OFF_MODE_FLAGS) then
    return "shutoff"
  end
  if FloModel.has_flag(mode, modes.bypass) then
    return "bypass"
  end
  if FloModel.has_flag(mode, modes.away) then
    return "away"
  end
  if FloModel.has_flag(mode, modes.home) then
    return "home"
  end
  if FloModel.has_flag(mode, modes.disabled) then
    return "disabled"
  end
  return nil
end

function FloModel.mode_status_name(valve)
  local mode = to_number(valve.mode)
  if mode == nil then
    return "unknown"
  end
  local exact = FloModel.MODE_NAMES[mode]
  if exact ~= nil then
    return exact
  end
  for _, flag in ipairs(FloModel.MODE_STATUS_PRIORITY) do
    if FloModel.has_flag(mode, flag) then
      return FloModel.MODE_FLAG_NAMES[flag]
    end
  end
  return "unknown_" .. tostring(mode)
end

function FloModel.mode_flag_names(valve)
  local mode = to_number(valve.mode)
  if mode == nil then
    return {}
  end
  local names = {}
  for flag, name in pairs(FloModel.MODE_FLAG_NAMES) do
    if FloModel.has_flag(mode, flag) then
      names[#names + 1] = name
    end
  end
  table.sort(names)
  return names
end

function FloModel.notification_flags(access)
  local raw = 0
  if access ~= nil then
    raw = to_number(access.notificationsList) or 0
  end
  local flags = {}
  for name, bit in pairs(FloModel.NOTIFICATION_FLAGS) do
    flags[name] = FloModel.has_flag(raw, bit)
  end
  return flags
end

function FloModel.is_water_flowing(valve)
  if valve.online ~= true then
    return false
  end
  local state = valve.flowState
  return state ~= nil and state ~= 1 and state ~= 8
end

-- Parse a FloLogic ISO-8601 timestamp as a UTC epoch. Returns nil when the
-- value is absent or malformed. os.time interprets tables as local time, so
-- the result is shifted by the controller's UTC offset.
function FloModel.parse_datetime_utc(value)
  if type(value) ~= "string" or value == "" then
    return nil
  end
  local y, mo, d, h, mi, s = value:match(
    "^(%d%d%d%d)%-(%d%d)%-(%d%d)[T ](%d%d):(%d%d):(%d%d)"
  )
  if y == nil then
    return nil
  end
  local as_local = os.time({
    year = tonumber(y), month = tonumber(mo), day = tonumber(d),
    hour = tonumber(h), min = tonumber(mi), sec = tonumber(s),
  })
  if as_local == nil then
    return nil
  end
  local now = os.time()
  local utc_offset = os.difftime(now, os.time(os.date("!*t", now)))
  return as_local + utc_offset
end

local function current_flow_limit_minutes(valve)
  local mode = FloModel.mode_name(valve)
  if mode == "home" then
    return to_number(valve.homeIntervalTime)
  elseif mode == "away" then
    return to_number(valve.awayIntervalTime)
  elseif mode == "bypass" then
    return to_number(valve.bypassTime)
  end
  return nil
end

function FloModel.flow_started_at(valve)
  if not FloModel.is_water_flowing(valve) then
    return nil
  end
  return FloModel.parse_datetime_utc(valve.lastNewFlow)
end

function FloModel.flow_elapsed_seconds(valve, now_epoch)
  local started = FloModel.flow_started_at(valve)
  if started == nil then
    return nil
  end
  local elapsed = (now_epoch or os.time()) - started
  if elapsed < 0 then
    return 0
  end
  return math.floor(elapsed)
end

function FloModel.shutoff_countdown_seconds(valve, now_epoch)
  if not FloModel.is_water_flowing(valve) then
    return nil
  end
  local limit = current_flow_limit_minutes(valve)
  if limit == nil or limit <= 0 then
    return nil
  end
  local started = FloModel.parse_datetime_utc(valve.lastNewFlow)
  if started == nil then
    return nil
  end
  local remaining = (started + limit * 60) - (now_epoch or os.time())
  if remaining < 0 then
    return 0
  end
  return math.floor(remaining)
end

function FloModel.advance_shutoff_warning(valve, access, now_epoch)
  if not FloModel.notification_flags(access).advance_shutoff then
    return false
  end
  local countdown = FloModel.shutoff_countdown_seconds(valve, now_epoch)
  if countdown == nil then
    return false
  end
  local pre_alert = to_number(valve.preAlertNoticeInterval) or 0
  return countdown >= 0 and countdown <= pre_alert * 60
end

function FloModel.active_scheduler_events(scheduler)
  local active = {}
  if type(scheduler) ~= "table" then
    return active
  end
  for _, event in ipairs(scheduler) do
    if type(event) == "table" and event.action ~= nil and event.actionPayload ~= nil then
      active[#active + 1] = event
    end
  end
  return active
end

-- Valve discovery mirrors the Home Assistant client: exclude explicit
-- gateways, prefer positively identified Connect valves, and otherwise fall
-- back to every non-gateway device (older payloads without type metadata).
function FloModel.controllable_valves(devices)
  if type(devices) ~= "table" or #devices == 0 then
    return {}
  end
  local candidates = {}
  for _, device in ipairs(devices) do
    if type(device) == "table" and device.isZGateway ~= true then
      candidates[#candidates + 1] = device
    end
  end
  local valves = {}
  for _, device in ipairs(candidates) do
    local type_name = string.lower(tostring(device.deviceTypeName or ""))
    if device.isZConnect == true
      or device.isAnyConnect == true
      or type_name:find("connect", 1, true) ~= nil
    then
      valves[#valves + 1] = device
    end
  end
  if #valves > 0 then
    return valves
  end
  return candidates
end

-- Primary-valve preference used when no explicit selection exists.
function FloModel.choose_valve(devices)
  local valves = FloModel.controllable_valves(devices)
  for _, valve in ipairs(valves) do
    if valve.isZConnect == true then
      return valve
    end
  end
  for _, valve in ipairs(valves) do
    if valve.isAnyConnect == true then
      return valve
    end
  end
  return valves[1]
end

function FloModel.find_valve(devices, needle)
  local want = tostring(needle)
  local want_folded = string.lower(want)
  for _, device in ipairs(devices) do
    if type(device) == "table" then
      if tostring(device.id) == want or tostring(device.uuid) == want then
        return device
      end
    end
  end
  for _, device in ipairs(devices) do
    if type(device) == "table" then
      if string.lower(tostring(device.id)) == want_folded
        or string.lower(tostring(device.uuid)) == want_folded
      then
        return device
      end
    end
  end
  return nil
end

function FloModel.mode_value(mode)
  local value = FloModel.VALVE_MODES[mode]
  if value == nil then
    local valid = {}
    for name, _ in pairs(FloModel.VALVE_MODES) do
      valid[#valid + 1] = name
    end
    table.sort(valid)
    error("Unknown FloLogic mode '" .. tostring(mode) .. "'; valid modes: " .. table.concat(valid, ", "))
  end
  return value
end

-- ============================================================================
-- bundled: src/signalr.lua
-- ============================================================================
-- ============================================================================
-- c4/src/signalr.lua — SignalR JSON-protocol codec and event dispatcher.
--
-- Pure logic (uses the global JSON table at call time). Defines the global
-- SignalR table only. No require, no return, no top-level execution.
-- Lua 5.1 safe: the record separator uses a decimal escape (\030 = \x1e).
-- ============================================================================

SignalR = SignalR or {}

SignalR.RECORD_SEPARATOR = "\030"

function SignalR.handshake_message()
  return '{"protocol":"json","version":1}' .. SignalR.RECORD_SEPARATOR
end

function SignalR.build_invoke(target, args)
  return JSON.encode({ type = 1, target = target, arguments = args or {} })
    .. SignalR.RECORD_SEPARATOR
end

-- Dispatcher matches hub events to one-shot waiters, like the Home Assistant
-- client's _events table. opts.on_event(target, arguments) observes every
-- event; opts.on_error(message) reports undecodable frames.
function SignalR.new_dispatcher(opts)
  opts = opts or {}
  local self = {
    _buffer = "",
    _waiters = {},
    _on_event = opts.on_event,
    _on_error = opts.on_error,
  }

  function self.wait_for(event_name, callback)
    local list = self._waiters[event_name]
    if list == nil then
      list = {}
      self._waiters[event_name] = list
    end
    list[#list + 1] = callback
    -- Returns a cancel function for timeouts.
    return function()
      local current = self._waiters[event_name]
      if current == nil then
        return
      end
      for i, fn in ipairs(current) do
        if fn == callback then
          table.remove(current, i)
          return
        end
      end
    end
  end

  function self.pending(event_name)
    local list = self._waiters[event_name]
    return list ~= nil and #list or 0
  end

  function self.fail_all(err)
    for event_name, list in pairs(self._waiters) do
      self._waiters[event_name] = {}
      for _, fn in ipairs(list) do
        fn(nil, err)
      end
    end
  end

  local function handle_frame(frame)
    if type(frame) ~= "table" or frame.type ~= 1 then
      return
    end
    local target = frame.target
    if target == nil or target == "" then
      return
    end
    local args = frame.arguments or {}
    local list = self._waiters[target]
    if list ~= nil and #list > 0 then
      local fn = table.remove(list, 1)
      fn(args, nil)
    end
    if self._on_event ~= nil then
      self._on_event(target, args)
    end
  end

  function self.feed(text)
    self._buffer = self._buffer .. text
    while true do
      local cut = self._buffer:find(SignalR.RECORD_SEPARATOR, 1, true)
      if cut == nil then
        return
      end
      local raw = self._buffer:sub(1, cut - 1)
      self._buffer = self._buffer:sub(cut + 1)
      if raw ~= "" then
        local ok, frame = pcall(JSON.decode, raw)
        if ok then
          handle_frame(frame)
        elseif self._on_error ~= nil then
          self._on_error("undecodable SignalR frame: " .. raw:sub(1, 120))
        end
      end
    end
  end

  return self
end

-- ============================================================================
-- bundled: src/websocket.lua
-- ============================================================================
-- ============================================================================
-- c4/src/websocket.lua — RFC 6455 client codec and handshake helpers.
--
-- Pure logic. Defines the global WS table only. No require, no return, no
-- top-level execution. Lua 5.1 safe (arithmetic-only bit handling).
--
-- Crypto and randomness are injected by the caller: on Control4 use
-- C4:Hash("SHA1", ...) and C4:Base64Encode; tests inject pure-Lua versions.
-- The actual socket belongs to the caller (a Director-managed TLS network
-- connection); this module only builds/parses bytes.
-- ============================================================================

WS = WS or {}

WS.GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
WS.OP_CONT = 0
WS.OP_TEXT = 1
WS.OP_BINARY = 2
WS.OP_CLOSE = 8
WS.OP_PING = 9
WS.OP_PONG = 10

local function bxor_byte(a, b)
  local result, bit = 0, 1
  for _ = 1, 8 do
    if (a % 2) ~= (b % 2) then
      result = result + bit
    end
    a = math.floor(a / 2)
    b = math.floor(b / 2)
    bit = bit * 2
  end
  return result
end

function WS.xor_mask(payload, mask)
  local out = {}
  for i = 1, #payload do
    out[i] = string.char(bxor_byte(payload:byte(i), mask[((i - 1) % 4) + 1]))
  end
  return table.concat(out)
end

-- Build the HTTP Upgrade request. key must be the Base64 of 16 random bytes.
function WS.build_handshake_request(host, path, key, extra_headers)
  local lines = {
    "GET " .. path .. " HTTP/1.1",
    "Host: " .. host,
    "Upgrade: websocket",
    "Connection: Upgrade",
    "Sec-WebSocket-Key: " .. key,
    "Sec-WebSocket-Version: 13",
  }
  if extra_headers ~= nil then
    for _, line in ipairs(extra_headers) do
      lines[#lines + 1] = line
    end
  end
  return table.concat(lines, "\r\n") .. "\r\n\r\n"
end

-- Expected Sec-WebSocket-Accept for a client key. sha1_fn(data) returns raw
-- bytes; b64_fn(data) returns Base64 text.
function WS.expected_accept(key, sha1_fn, b64_fn)
  return b64_fn(sha1_fn(key .. WS.GUID))
end

-- Parse a server handshake response. Returns accept_key, bytes_consumed on
-- success; nil, "need_more" when the headers are incomplete; nil, err otherwise.
function WS.parse_handshake_response(buffer)
  local cut = buffer:find("\r\n\r\n", 1, true)
  if cut == nil then
    return nil, "need_more"
  end
  local head = buffer:sub(1, cut - 1)
  local status = head:match("^HTTP/%S+%s+(%d+)")
  if status ~= "101" then
    return nil, "websocket upgrade rejected: " .. (status or "?")
  end
  -- Match the header name case-insensitively but keep the original value:
  -- Base64 is case-sensitive.
  local accept = nil
  for line in (head .. "\r\n"):gmatch("([^\r\n]*)\r\n") do
    local name, value = line:match("^([^:]+):%s*(.-)%s*$")
    if name ~= nil and name:lower() == "sec-websocket-accept" then
      accept = value
      break
    end
  end
  if accept == nil or accept == "" then
    return nil, "websocket upgrade missing Sec-WebSocket-Accept"
  end
  return accept, cut + 3
end

-- Build a single masked client frame (FIN set). mask is 4 byte numbers.
function WS.build_client_frame(payload, mask, opcode)
  opcode = opcode or WS.OP_TEXT
  local len = #payload
  local head
  if len < 126 then
    head = string.char(128 + opcode, 128 + len)
  elseif len < 65536 then
    head = string.char(
      128 + opcode, 128 + 126,
      math.floor(len / 256) % 256, len % 256
    )
  else
    local high = math.floor(len / 4294967296)
    local low = len % 4294967296
    head = string.char(
      128 + opcode, 128 + 127,
      0, 0, 0, 0,
      math.floor(low / 16777216) % 256,
      math.floor(low / 65536) % 256,
      math.floor(low / 256) % 256,
      low % 256
    )
    if high ~= 0 then
      error("websocket payload too large")
    end
  end
  return head
    .. string.char(mask[1], mask[2], mask[3], mask[4])
    .. WS.xor_mask(payload, mask)
end

function WS.build_close_payload(code, reason)
  code = code or 1000
  return string.char(math.floor(code / 256) % 256, code % 256) .. (reason or "")
end

-- Incremental server-frame parser. Callbacks:
--   on_message(payload, is_binary)  -- reassembled text/binary message
--   on_ping(payload) -> true to auto-send pong via send_frame
--   on_pong(payload)
--   on_close(code, reason)
--   on_error(message)
--   send_frame(payload, opcode) -- masked client-frame sender; nil disables pong
function WS.new_parser(callbacks)
  callbacks = callbacks or {}
  local self = { _buffer = "", _frag_opcode = nil, _frag_parts = {} }

  local function parse_one()
    local buf, blen = self._buffer, #self._buffer
    if blen < 2 then
      return nil -- need more
    end
    local b1, b2 = buf:byte(1), buf:byte(2)
    local fin = b1 >= 128
    local opcode = b1 % 16
    if b1 % 128 >= 16 then
      return nil, "websocket RSV bits set without negotiated extensions"
    end
    local masked = b2 >= 128
    local len = b2 % 128
    local pos = 3
    if len == 126 then
      if blen < 4 then
        return nil
      end
      len = buf:byte(3) * 256 + buf:byte(4)
      pos = 5
    elseif len == 127 then
      if blen < 10 then
        return nil
      end
      local high = buf:byte(3) * 16777216 + buf:byte(4) * 65536
        + buf:byte(5) * 256 + buf:byte(6)
      local low = buf:byte(7) * 16777216 + buf:byte(8) * 65536
        + buf:byte(9) * 256 + buf:byte(10)
      if high ~= 0 then
        return nil, "websocket frame too large"
      end
      len = low
      pos = 11
    end
    local mask = nil
    if masked then
      if blen < pos + 3 then
        return nil
      end
      mask = { buf:byte(pos, pos + 3) }
      pos = pos + 4
    end
    if blen < pos + len - 1 then
      return nil -- need more
    end
    local payload = buf:sub(pos, pos + len - 1)
    if mask ~= nil then
      payload = WS.xor_mask(payload, mask)
    end
    self._buffer = buf:sub(pos + len)
    return { fin = fin, opcode = opcode, payload = payload }
  end

  function self.feed(data)
    self._buffer = self._buffer .. data
    while true do
      local frame, err = parse_one()
      if err ~= nil then
        if callbacks.on_error ~= nil then
          callbacks.on_error(err)
        end
        return
      end
      if frame == nil then
        return -- need more data
      end
      local op, payload = frame.opcode, frame.payload
      if op == WS.OP_CONT then
        if self._frag_opcode == nil then
          if callbacks.on_error ~= nil then
            callbacks.on_error("stray websocket continuation frame")
          end
          return
        end
        self._frag_parts[#self._frag_parts + 1] = payload
        if frame.fin then
          local message = table.concat(self._frag_parts)
          local is_binary = self._frag_opcode == WS.OP_BINARY
          self._frag_opcode, self._frag_parts = nil, {}
          if callbacks.on_message ~= nil then
            callbacks.on_message(message, is_binary)
          end
        end
      elseif op == WS.OP_TEXT or op == WS.OP_BINARY then
        if self._frag_opcode ~= nil then
          if callbacks.on_error ~= nil then
            callbacks.on_error("interleaved websocket data frame")
          end
          return
        end
        if frame.fin then
          if callbacks.on_message ~= nil then
            callbacks.on_message(payload, op == WS.OP_BINARY)
          end
        else
          self._frag_opcode, self._frag_parts = op, { payload }
        end
      elseif op == WS.OP_PING then
        local want_pong = true
        if callbacks.on_ping ~= nil then
          want_pong = callbacks.on_ping(payload)
        end
        if want_pong and callbacks.send_frame ~= nil then
          callbacks.send_frame(payload, WS.OP_PONG)
        end
      elseif op == WS.OP_PONG then
        if callbacks.on_pong ~= nil then
          callbacks.on_pong(payload)
        end
      elseif op == WS.OP_CLOSE then
        local code, reason = 1005, ""
        if #payload >= 2 then
          code = payload:byte(1) * 256 + payload:byte(2)
          reason = payload:sub(3)
        end
        if callbacks.on_close ~= nil then
          callbacks.on_close(code, reason)
        end
        return
      else
        if callbacks.on_error ~= nil then
          callbacks.on_error("unknown websocket opcode " .. tostring(op))
        end
        return
      end
    end
  end

  return self
end

-- ============================================================================
-- bundled: src/flologic.lua
-- ============================================================================
-- ============================================================================
-- c4/src/flologic.lua — FloLogic SignalR cloud session (transport-injected).
--
-- Mirrors custom_components/flologic/api.py one-shot (non-persistent) flows:
-- negotiate -> websocket -> login -> fetch metadata | send command -> close.
-- No Control4 globals are referenced here; the caller injects http_post, a
-- raw tcp byte transport, timers, randomness, and crypto. Defines the global
-- FloLogic table only. Lua 5.1 safe.
-- ============================================================================

FloLogic = FloLogic or {}

FloLogic.OS_PLATFORM = "Android"
FloLogic.APP_VERSION = "control4"

local function pct_encode(text)
  return tostring(text):gsub("[^A-Za-z0-9_%.%-%~]", function(ch)
    return string.format("%%%02X", string.byte(ch))
  end)
end

-- Split an https:// hub URL into host, port, and signalr base path.
function FloLogic.parse_hub_url(hub_url)
  local host, port, path = hub_url:match("^https?://([^:/%s]+):?(%d*)([^%s]*)")
  if host == nil then
    return nil, "bad hub URL: " .. tostring(hub_url)
  end
  port = tonumber(port) or 443
  path = path or ""
  path = path:gsub("/+$", "")
  if not path:lower():find("/signalr$") then
    path = path .. "/signalr"
  end
  if path == "" then
    path = "/signalr"
  end
  return { host = host, port = port, path = path }
end

function FloLogic.new_session(opts)
  local self = {
    _email = opts.email,
    _password = opts.password,
    _device_name = opts.device_name or "Control4",
    _device_code = opts.device_code or "AND-c4-custom-001",
    _device_token = opts.device_token or "c4-custom-token",
    _relog_token = opts.relog_token or "",
    _http_post = opts.http_post,
    _tcp_open = opts.tcp_open,
    _set_timeout = opts.set_timeout,
    _client_key = opts.client_key,
    _sha1 = opts.sha1,
    _b64encode = opts.b64encode,
    _random_mask = opts.random_mask,
    _log = opts.log or function() end,
    _tcp = nil,
    _dispatcher = nil,
    _ws_parser = nil,
    _done = false,
    _timers = {},
    _user = nil,
    _devices = nil,
    _late_valve = nil,
    relog_token = opts.relog_token or "",
  }

  function self._log_debug(msg)
    self._log("DEBUG: " .. msg)
  end

  function self._after(ms, fn)
    local cancel = self._set_timeout(ms, function()
      if not self._done then
        fn()
      end
    end)
    self._timers[#self._timers + 1] = cancel
    return cancel
  end

  function self._cancel_timers()
    for _, cancel in ipairs(self._timers) do
      pcall(cancel)
    end
    self._timers = {}
  end

  function self._finish(err, result, callback)
    if self._done then
      return
    end
    self._done = true
    self._cancel_timers()
    if self._dispatcher ~= nil then
      self._dispatcher.fail_all(err or "closed")
    end
    self.close()
    callback(err, result)
  end

  function self.close()
    if self._tcp ~= nil then
      local tcp = self._tcp
      self._tcp = nil
      pcall(function()
        tcp.close()
      end)
    end
  end

  function self._send_text(text)
    if self._tcp == nil then
      return false
    end
    local mask = self._random_mask()
    local frame = WS.build_client_frame(text, mask, WS.OP_TEXT)
    self._tcp.send(frame)
    return true
  end

  function self._invoke(target, args)
    self._log_debug("invoke " .. target)
    return self._send_text(SignalR.build_invoke(target, args))
  end

  -- Wait for one hub event with a timeout (ms). cb(args) on success,
  -- fail_cb(err) on timeout. Returns immediately if the session finished.
  function self._wait_for(event_name, timeout_ms, cb, fail_cb)
    local cancel_waiter = nil
    local cancel_timer = nil
    local settled = false
    local function settle(args, err)
      if settled or self._done then
        return
      end
      settled = true
      if cancel_timer ~= nil then
        pcall(cancel_timer)
      end
      if err ~= nil then
        fail_cb(err)
      else
        cb(args)
      end
    end
    cancel_waiter = self._dispatcher.wait_for(event_name, function(args, err)
      settle(args, err)
    end)
    cancel_timer = self._after(timeout_ms, function()
      if cancel_waiter ~= nil then
        cancel_waiter()
      end
      settle(nil, "timeout:" .. event_name)
    end)
  end

  function self._negotiate(hub, on_ok, on_fail)
    local url = "https://" .. hub.host .. ":" .. tostring(hub.port) .. hub.path .. "/negotiate"
    -- Omit the default port for cosmetics; harmless either way.
    if hub.port == 443 then
      url = "https://" .. hub.host .. hub.path .. "/negotiate"
    end
    local headers = {
      userDeviceCode = self._device_code,
      userDeviceToken = self._device_token,
      relogToken = self._relog_token,
      OsPlatform = FloLogic.OS_PLATFORM,
      AppVer = FloLogic.APP_VERSION,
      DeviceName = self._device_name,
    }
    self._log_debug("negotiate " .. url)
    self._http_post(url, "", headers, function(err, data, code)
      if self._done then
        return
      end
      if err ~= nil then
        on_fail("http:" .. tostring(err))
        return
      end
      if code == 401 or code == 403 then
        on_fail("auth")
        return
      end
      if code == nil or code < 200 or code >= 300 then
        on_fail("http:" .. tostring(code))
        return
      end
      local ok, payload = pcall(JSON.decode, data or "")
      if not ok or type(payload) ~= "table" then
        on_fail("http:bad-negotiate-body")
        return
      end
      local token = payload.connectionToken or payload.connectionId
      if token == nil or token == "" then
        on_fail("http:no-connection-token")
        return
      end
      on_ok(token)
    end)
  end

  function self._open_websocket(hub, token, on_ok, on_fail)
    local ws_path = hub.path .. "?id=" .. pct_encode(token)
    local key = self._client_key()
    local expected = WS.expected_accept(key, self._sha1, self._b64encode)
    local handshake_done = false
    local handshake_buffer = ""
    local parser = WS.new_parser({
      on_message = function(payload, is_binary)
        if is_binary then
          if not self._done then
            on_fail("ws:binary-frame")
          end
          return
        end
        self._dispatcher.feed(payload)
      end,
      send_frame = function(payload, opcode)
        if self._tcp ~= nil then
          self._tcp.send(WS.build_client_frame(payload, self._random_mask(), opcode))
        end
      end,
      on_close = function(code, _reason)
        if not self._done then
          on_fail("ws:closed-" .. tostring(code))
        end
      end,
      on_error = function(msg)
        if not self._done then
          on_fail("ws:" .. tostring(msg))
        end
      end,
    })
    self._ws_parser = parser
    -- The transport may report on_open synchronously (before tcp_open
    -- returns), so the handshake send is deferred until self._tcp exists.
    local opened, handshake_sent = false, false
    local function send_handshake()
      if handshake_sent or self._done or self._tcp == nil then
        return
      end
      handshake_sent = true
      local request = WS.build_handshake_request(
        hub.host .. ":" .. tostring(hub.port), ws_path, key
      )
      self._tcp.send(request)
    end
    local tcp, tcp_err = self._tcp_open(hub.host, hub.port, {
      on_open = function()
        opened = true
        send_handshake()
      end,
      on_data = function(bytes)
        if self._done then
          return
        end
        if not handshake_done then
          handshake_buffer = handshake_buffer .. bytes
          local accept, consumed_or_err = WS.parse_handshake_response(handshake_buffer)
          if accept == nil and consumed_or_err == "need_more" then
            return
          end
          if accept == nil then
            on_fail("ws:" .. tostring(consumed_or_err))
            return
          end
          if accept ~= expected then
            on_fail("ws:bad-accept-key")
            return
          end
          handshake_done = true
          local rest = handshake_buffer:sub(consumed_or_err + 1)
          handshake_buffer = ""
          if not self._send_text(SignalR.handshake_message()) then
            on_fail("ws:send-failed")
            return
          end
          on_ok()
          if rest ~= "" then
            parser.feed(rest)
          end
        else
          parser.feed(bytes)
        end
      end,
      on_close = function()
        if not self._done then
          on_fail("ws:tcp-closed")
        end
      end,
      on_error = function(msg)
        if not self._done then
          on_fail("ws:" .. tostring(msg))
        end
      end,
    })
    if tcp == nil then
      on_fail("ws:" .. tostring(tcp_err or "tcp-open-failed"))
      return
    end
    self._tcp = tcp
    if opened then
      send_handshake()
    end
  end

  function self._login(on_ok, on_fail)
    self._log_debug("login as " .. self._email)
    self._wait_for("LoggedIn", 30000, function(args)
      local user = args[1]
      if type(user) ~= "table" then
        on_fail("auth")
        return
      end
      self._user = user
      if user.relogToken ~= nil and user.relogToken ~= "" then
        self._relog_token = user.relogToken
        self.relog_token = user.relogToken
      end
      -- Fast path: a ValveSent usually follows immediately. Fall back to
      -- RefreshValveArray after 3s, merging a late ValveSent if one lands.
      self._late_valve = nil
      local got_valve = false
      local function use_devices(devices)
        if got_valve then
          return
        end
        got_valve = true
        self._devices = devices
        on_ok(user, devices)
      end
      self._wait_for("ValveSent", 3000, function(valve_args)
        local valve = valve_args[1]
        if type(valve) == "table" then
          use_devices({ valve })
        else
          self._refresh_valve_array(user, use_devices, on_fail)
        end
      end, function(_timeout_err)
        self._refresh_valve_array(user, use_devices, on_fail)
      end)
    end, on_fail)
    if not self._invoke("Login", { self._email, self._password, self._device_name, JSON.null }) then
      on_fail("ws:send-failed")
    end
  end

  function self._refresh_valve_array(user, on_ok, on_fail)
    self._wait_for("ValveArraySent", 30000, function(args)
      local devices = args[1]
      if type(devices) ~= "table" then
        devices = {}
      end
      local clean = {}
      for _, device in ipairs(devices) do
        if type(device) == "table" then
          clean[#clean + 1] = device
        end
      end
      if self._late_valve ~= nil then
        local seen = false
        for _, device in ipairs(clean) do
          if device.id == self._late_valve.id then
            seen = true
            break
          end
        end
        if not seen then
          clean[#clean + 1] = self._late_valve
        end
      end
      on_ok(clean)
    end, on_fail)
    if not self._invoke("RefreshValveArray", { user }) then
      on_fail("ws:send-failed")
    end
  end

  local function observe_valve_sent(self_ref, target, args)
    if target == "ValveSent" and args[1] ~= nil and type(args[1]) == "table" then
      self_ref._late_valve = args[1]
    elseif target == "ErrorOccured" then
      self_ref._log_debug("cloud error event")
    end
  end

  function self._connect(hub_url, on_ready, on_fail)
    local hub, hub_err = FloLogic.parse_hub_url(hub_url)
    if hub == nil then
      on_fail(hub_err)
      return
    end
    self._dispatcher = SignalR.new_dispatcher({
      on_event = function(target, args)
        observe_valve_sent(self, target, args)
      end,
      on_error = function(msg)
        self._log_debug(msg)
      end,
    })
    self._negotiate(hub, function(token)
      self._open_websocket(hub, token, function()
        self._login(function(user, devices)
          on_ready(user, devices)
        end, on_fail)
      end, on_fail)
    end, on_fail)
  end

  -- Resolve the effective valve. A nil/blank selection means the primary
  -- valve. When a selection is not among the login devices, the login fast
  -- path may have sent only the primary valve, so the full array is fetched
  -- before reporting valve-not-found.
  function self._ensure_valve(user, devices, selected, on_ok, on_fail)
    local valves = FloModel.controllable_valves(devices)
    local valve = nil
    if selected == nil or selected == "" then
      valve = FloModel.choose_valve(devices)
    else
      valve = FloModel.find_valve(valves, selected)
        or FloModel.find_valve(devices, selected)
    end
    if valve ~= nil then
      on_ok(valve, devices, valves)
      return
    end
    if selected == nil or selected == "" then
      on_fail("no-valve")
      return
    end
    self._refresh_valve_array(user, function(full)
      local full_valves = FloModel.controllable_valves(full)
      local found = FloModel.find_valve(full_valves, selected)
        or FloModel.find_valve(full, selected)
      if found == nil then
        on_fail("valve-not-found")
        return
      end
      on_ok(found, full, full_valves)
    end, on_fail)
  end

  function self._fetch_access(user, valve, on_ok, on_fail)
    self._wait_for("UserAccessesSent", 30000, function(args)
      local accesses = args[1]
      local access = nil
      if type(accesses) == "table" then
        for _, row in ipairs(accesses) do
          if type(row) == "table" and row.valveId == valve.id then
            access = row
            break
          end
        end
      end
      on_ok(access)
    end, on_fail)
    if not self._invoke("RequestUserAccesses", { user }) then
      on_fail("ws:send-failed")
    end
  end

  function self._fetch_scheduler(user, valve, on_ok, on_fail)
    self._wait_for("SchedulerEventsSent", 30000, function(args)
      local rows = args[1]
      if type(rows) ~= "table" then
        rows = {}
      end
      on_ok(rows)
    end, function(_timeout_err)
      on_ok({}) -- scheduler is optional; timeouts degrade to empty
    end)
    if not self._invoke("RequestSchedulerEvents", { user.id, valve.id }) then
      on_fail("ws:send-failed")
    end
  end

  function self._fetch_notifications(user, valve, on_ok, on_fail)
    -- Per-valve history only. There is deliberately no account-wide retry:
    -- an empty history must never pull in another site's notifications.
    self._wait_for("NotificationsHistorySent", 30000, function(args)
      local rows = args[1]
      if type(rows) == "table" then
        on_ok(rows)
      else
        on_ok({})
      end
    end, function(_timeout_err)
      on_ok({})
    end)
    if not self._invoke("RefreshValvesNotificationsHistory", { user.id, { valve.id } }) then
      on_fail("ws:send-failed")
    end
  end

  -- Fetch one poll snapshot for the selected valve. selected may be a valve
  -- id, uuid, or unique-id prefix, or nil for the primary valve.
  -- cb(err, snapshot) with snapshot = { user, devices, valves, valve,
  -- access, scheduler, notifications }.
  function self.fetch_snapshot(hub_url, selected, cb)
    local function fail(err)
      self._finish(err, nil, cb)
    end
    self._connect(hub_url, function(user, devices)
      self._ensure_valve(user, devices, selected, function(valve, all_devices, valves)
        self._fetch_access(user, valve, function(access)
          self._fetch_scheduler(user, valve, function(scheduler)
            self._fetch_notifications(user, valve, function(notifications)
              self._finish(nil, {
                user = user,
                devices = all_devices,
                valves = valves,
                valve = valve,
                access = access,
                scheduler = scheduler,
                notifications = notifications,
              }, cb)
            end, fail)
          end, fail)
        end, fail)
      end, fail)
    end, fail)
  end

  -- Send one state-change command. fields is a flat table of cloud values.
  function self.send_command(hub_url, selected, fields, cb)
    local function fail(err)
      self._finish(err, nil, cb)
    end
    self._connect(hub_url, function(user, devices)
      self._ensure_valve(user, devices, selected, function(valve)
        local command = {
          active = true,
          created = os.date("!%Y-%m-%dT%H:%M:%SZ"),
          userId = user.id,
          valveId = valve.id,
        }
        for k, v in pairs(fields) do
          command[k] = v
        end
        self._wait_for("StateChangeResult", 45000, function(_args)
          self._finish(nil, { valve = valve }, cb)
        end, function(err)
          self._finish(err, nil, cb)
        end)
        if not self._invoke("RequestStateChange", { user, valve, command }) then
          self._finish("ws:send-failed", nil, cb)
        end
      end, fail)
    end, fail)
  end

  return self
end

-- ============================================================================
-- bundled: src/main.lua
-- ============================================================================
-- ============================================================================
-- c4/src/main.lua — Control4 Director glue: lifecycle, properties, commands,
-- events, timers, and the C4 network/HTTP transport for FloLogic sessions.
--
-- Bundled LAST after json/model/signalr/websocket/flologic. Defines Director
-- entry points (OnDriverInit, OnDriverLateInit, ExecuteCommand, ...) plus
-- module state. No top-level C4 calls (safe to load in tests with a stub C4).
-- Lua 5.1 safe.
-- ============================================================================

FLOGIC_DRIVER_VERSION = "2026090601"
FLOGIC_DEFAULT_HUB = "https://hub-cloudapps-prod.azurewebsites.net"
FLOGIC_BINDING_FIRST = 6100
FLOGIC_BINDING_LAST = 6199
FLOGIC_MIN_POLL_SECONDS = 30
FLOGIC_MAX_POLL_SECONDS = 3600
FLOGIC_LOCAL_TICK_MS = 5000

-- Property names (must match driver.xml).
FLOGIC_PROP_DEBUG = "Debug Mode"
FLOGIC_PROP_EMAIL = "Email"
FLOGIC_PROP_PASSWORD = "Password"
FLOGIC_PROP_HUB = "Hub URL"
FLOGIC_PROP_POLL = "Poll Interval"
FLOGIC_PROP_PICKER = "Select Valve"
FLOGIC_PROP_OVERRIDE = "Valve ID Override"
FLOGIC_PROP_CONNECTION = "Connection"

-- Event names (must match driver.xml).
FLOGIC_EV_FLOW_STARTED = "Flow Started"
FLOGIC_EV_FLOW_STOPPED = "Flow Stopped"
FLOGIC_EV_WATER_OFF = "Water Off Detected"
FLOGIC_EV_WATER_OFF_CLEAR = "Water Off Cleared"
FLOGIC_EV_WARNING = "Warning Alert"
FLOGIC_EV_WARNING_CLEAR = "Warning Cleared"
FLOGIC_EV_CRITICAL = "Critical Fault"
FLOGIC_EV_CRITICAL_CLEAR = "Critical Cleared"
FLOGIC_EV_MODE_CHANGED = "Mode Changed"
FLOGIC_EV_ADVANCE = "Advance Shutoff Warning"
FLOGIC_EV_CONN_LOST = "Connection Lost"
FLOGIC_EV_CONN_RESTORED = "Connection Restored"

-- Driver state. One session at a time; commands queue behind a running poll.
flogic_state = flogic_state or {
  binding = nil,
  hub_host = nil,
  hub_port = nil,
  poll_timer = nil,
  tick_timer = nil,
  busy = false,
  command_queue = {},
  last_snapshot = nil,
  last_connection_ok = nil,
  last_mode = nil,
  last_flowing = nil,
  last_water_off = nil,
  last_warning = nil,
  last_critical = nil,
  last_advance = nil,
  relog_token = "",
  sha1_digest = nil,
  tcp_callbacks = nil,
  last_picker_labels = nil,
}

local function flogic_log(message)
  if Properties ~= nil and Properties[FLOGIC_PROP_DEBUG] == "On" then
    print("[flologic] " .. tostring(message))
  end
end

local function flogic_log_warn(message)
  print("[flologic] WARN: " .. tostring(message))
end

local function flogic_prop(name)
  if Properties == nil then
    return ""
  end
  return Properties[name] or ""
end

local function flogic_set_prop(name, value)
  if value == nil then
    value = ""
  end
  C4:UpdateProperty(name, tostring(value))
end

-- --- Transport: Director-managed TLS TCP connection -----------------------
-- One dynamic binding is allocated at startup and reused for every session
-- (sessions run serially, so one connection suffices and nothing leaks).

local function flogic_find_free_binding()
  for id = FLOGIC_BINDING_FIRST, FLOGIC_BINDING_LAST do
    local ok, address = pcall(function()
      return C4:GetBindingAddress(id)
    end)
    if not ok or address == nil or address == "" then
      return id
    end
  end
  return nil
end

local function flogic_ensure_binding(host, port)
  local st = flogic_state
  if st.binding ~= nil and st.hub_host == host and st.hub_port == port then
    return st.binding
  end
  if st.binding == nil then
    local id = flogic_find_free_binding()
    if id == nil then
      return nil, "no free network binding"
    end
    st.binding = id
  end
  st.hub_host, st.hub_port = host, port
  C4:CreateNetworkConnection(st.binding, host, "SSL")
  -- NOTE: VERIFY_MODE none. Director documents no system CA bundle for raw
  -- socket connections (unlike the URL APIs), so peer verification would
  -- fail closed and brick the driver. The negotiate POST still runs over
  -- verified platform TLS. Revisit if Director documents CA handling here.
  C4:NetPortOptions(st.binding, port, "TCP/SSL", {
    AUTO_CONNECT = false,
    MONITOR_CONNECTION = false,
    KEEP_CONNECTION = false,
    KEEP_ALIVE = true,
    VERIFY_MODE = "none",
  })
  return st.binding
end

function ReceivedFromNetwork(idBinding, nPort, strData)
  local st = flogic_state
  if st.binding == idBinding and st.tcp_callbacks ~= nil then
    st.tcp_callbacks.on_data(strData)
  end
end

function OnConnectionStatusChanged(idBinding, nPort, strStatus)
  local st = flogic_state
  if st.binding ~= idBinding or st.tcp_callbacks == nil then
    return
  end
  if strStatus == "ONLINE" then
    st.tcp_callbacks.on_open()
  else
    st.tcp_callbacks.on_close()
  end
end

local function flogic_tcp_open(host, port, callbacks)
  local binding, err = flogic_ensure_binding(host, port)
  if binding == nil then
    return nil, err
  end
  flogic_state.tcp_callbacks = callbacks
  C4:NetConnect(binding, port)
  local handle = {}
  function handle.send(bytes)
    C4:SendToNetwork(binding, port, bytes)
  end
  function handle.close()
    if flogic_state.tcp_callbacks == callbacks then
      flogic_state.tcp_callbacks = nil
    end
    C4:NetDisconnect(binding, port)
  end
  return handle
end

-- --- Transport: platform HTTPS for the negotiate step ----------------------

local function flogic_http_post(url, body, headers, cb)
  -- urlPost delivers (ticket-or-error, data, code, headers); a numeric
  -- first argument is a request ticket, not a failure.
  C4:urlPost(url, body, headers, false, function(strError, strData, nCode, _tHeaders)
    if type(strError) == "string" and strError ~= "" then
      cb(strError, nil, nCode)
    else
      cb(nil, strData or "", nCode)
    end
  end)
end

-- --- Crypto / randomness (platform-backed, probed once) --------------------

local function flogic_probe_sha1()
  for _, name in ipairs({ "SHA1", "sha1", "SHA-1" }) do
    local ok, result, err = pcall(function()
      return C4:Hash(name, "test", { return_encoding = "NONE", data_encoding = "NONE" })
    end)
    if ok and result ~= nil and err == nil and #result == 20 then
      return name
    end
  end
  return nil
end

local function flogic_sha1(data)
  local out, err = C4:Hash(
    flogic_state.sha1_digest, data, { return_encoding = "NONE", data_encoding = "NONE" }
  )
  if out == nil then
    error("C4:Hash failed: " .. tostring(err))
  end
  return out
end

local function flogic_random_mask()
  return {
    math.random(0, 255), math.random(0, 255),
    math.random(0, 255), math.random(0, 255),
  }
end

local function flogic_client_key()
  local bytes = {}
  for _ = 1, 16 do
    bytes[#bytes + 1] = string.char(math.random(0, 255))
  end
  return C4:Base64Encode(table.concat(bytes))
end

-- --- Session orchestration --------------------------------------------------

local function flogic_new_session()
  return FloLogic.new_session({
    email = flogic_prop(FLOGIC_PROP_EMAIL),
    password = flogic_prop(FLOGIC_PROP_PASSWORD),
    http_post = flogic_http_post,
    tcp_open = flogic_tcp_open,
    set_timeout = function(ms, fn)
      local timer = C4:SetTimer(ms, function(t)
        t:Cancel()
        fn()
      end, false)
      return function()
        timer:Cancel()
      end
    end,
    client_key = flogic_client_key,
    sha1 = flogic_sha1,
    b64encode = function(data)
      return C4:Base64Encode(data)
    end,
    random_mask = flogic_random_mask,
    relog_token = flogic_state.relog_token,
    log = flogic_log,
  })
end

local function flogic_hub_url()
  local url = flogic_prop(FLOGIC_PROP_HUB)
  if url == nil or url == "" then
    url = FLOGIC_DEFAULT_HUB
  end
  return url
end

-- Effective valve selection: manual override wins, else the picker label's
-- "(id)" suffix, else blank (primary valve).
local function flogic_selection()
  local override = flogic_prop(FLOGIC_PROP_OVERRIDE)
  if override ~= nil and override:match("%S") ~= nil then
    return override:match("^%s*(.-)%s*$")
  end
  local picked = flogic_prop(FLOGIC_PROP_PICKER)
  if picked ~= nil then
    local id = picked:match("%(([^%)]+)%)%s*$")
    if id ~= nil then
      return id
    end
  end
  return ""
end

local function flogic_fire(name)
  flogic_log("event: " .. name)
  C4:FireEvent(name)
end

local function flogic_set_connection(ok, detail)
  local st = flogic_state
  if ok then
    flogic_set_prop(FLOGIC_PROP_CONNECTION, "Online")
  else
    flogic_set_prop(FLOGIC_PROP_CONNECTION, "Offline: " .. tostring(detail or "error"))
  end
  if st.last_connection_ok ~= nil and st.last_connection_ok ~= ok then
    if ok then
      flogic_fire(FLOGIC_EV_CONN_RESTORED)
    else
      flogic_fire(FLOGIC_EV_CONN_LOST)
    end
  end
  st.last_connection_ok = ok
end

local function flogic_describe_error(err)
  err = tostring(err or "error")
  if err == "auth" then
    return "authentication failed"
  end
  if err == "valve-not-found" then
    return "selected valve not on account"
  end
  if err == "no-valve" then
    return "no controllable valve"
  end
  return err
end

local function flogic_valve_label(valve)
  return FloModel.valve_name(valve) .. " (" .. tostring(valve.id) .. ")"
end

local function flogic_update_picker(devices)
  local valves = FloModel.controllable_valves(devices)
  local labels = {}
  for _, valve in ipairs(valves) do
    labels[#labels + 1] = flogic_valve_label(valve)
  end
  local current = flogic_prop(FLOGIC_PROP_PICKER)
  local keep = nil
  for _, label in ipairs(labels) do
    if label == current then
      keep = current
      break
    end
  end
  if #labels > 0 then
    -- Only push the list when it changed: re-pushing an identical list on
    -- every poll risks feedback through OnPropertyChanged on some OS builds.
    local joined = table.concat(labels, ",")
    if joined ~= flogic_state.last_picker_labels then
      flogic_state.last_picker_labels = joined
      C4:UpdatePropertyList(FLOGIC_PROP_PICKER, joined, keep or labels[1])
    end
  end
  local lines = {}
  for _, valve in ipairs(valves) do
    lines[#lines + 1] = tostring(valve.id) .. ": " .. FloModel.valve_name(valve)
  end
  flogic_set_prop("Available Valves", table.concat(lines, " | "))
end

local function flogic_num(value)
  if value == nil or value == "" then
    return ""
  end
  return tostring(value)
end

local function flogic_update_properties(snap)
  local valve, access = snap.valve, snap.access
  local now = os.time()
  local elapsed = FloModel.flow_elapsed_seconds(valve, now)
  local countdown = FloModel.shutoff_countdown_seconds(valve, now)
  local flow_state = FloModel.FLOW_STATE_NAMES[valve.flowState]
  flogic_set_prop("Valve Name", FloModel.valve_name(valve))
  flogic_set_prop("Mode", FloModel.mode_status_name(valve))
  flogic_set_prop("Flow State", flow_state or flogic_num(valve.flowState))
  if FloModel.is_water_flowing(valve) then
    flogic_set_prop("Water Flowing", "Yes")
  else
    flogic_set_prop("Water Flowing", "No")
  end
  flogic_set_prop("Temperature", flogic_num(valve.temperature))
  flogic_set_prop("Battery Level", flogic_num(valve.batteryLevel))
  flogic_set_prop("Signal Strength", flogic_num(valve.signalStrength))
  flogic_set_prop("Current Flow", flogic_num(valve.currentFlow))
  flogic_set_prop("Home Limit", flogic_num(valve.homeIntervalTime))
  flogic_set_prop("Away Limit", flogic_num(valve.awayIntervalTime))
  flogic_set_prop("Bypass Time", flogic_num(valve.bypassTime))
  flogic_set_prop("Auto Away", flogic_num(valve.autoAwayTime))
  flogic_set_prop("Temp Alert", flogic_num(valve.lowTemperatureAlert))
  flogic_set_prop("Temp Shutoff", flogic_num(valve.lowTemperatureLimit))
  flogic_set_prop("Pre-Alert", flogic_num(valve.preAlertNoticeInterval))
  flogic_set_prop("No-Flow Notice", flogic_num(valve.noFlowNoticeInterval))
  flogic_set_prop("Flow Sensitivity", flogic_num(valve.dripRate))
  flogic_set_prop("Shutoff Countdown", flogic_num(countdown))
  flogic_set_prop("Flow Elapsed", flogic_num(elapsed))
  flogic_set_prop("Scheduler Events", tostring(#FloModel.active_scheduler_events(snap.scheduler)))
  flogic_set_prop("Notifications", tostring(#(snap.notifications or {})))
  flogic_set_prop("Last Update", os.date("%Y-%m-%d %H:%M:%S"))
  if access ~= nil then
    local flags = FloModel.notification_flags(access)
    flogic_log("notify advance_shutoff=" .. tostring(flags.advance_shutoff))
  end
end

local function flogic_process_edges(snap)
  local st = flogic_state
  local valve, access = snap.valve, snap.access
  local mode = FloModel.mode_status_name(valve)
  local flowing = FloModel.is_water_flowing(valve)
  local raw_mode = tonumber(valve.mode)
  local water_off = raw_mode ~= nil and FloModel.has_any_flag(raw_mode, FloModel.WATER_OFF_MODE_FLAGS)
  local warning = raw_mode ~= nil and FloModel.has_any_flag(raw_mode, FloModel.WARNING_ALERT_MODE_FLAGS)
  local critical = raw_mode ~= nil and FloModel.has_any_flag(raw_mode, FloModel.CRITICAL_MODE_FLAGS)
  local advance = FloModel.advance_shutoff_warning(valve, access)
  local first = st.last_mode == nil
  if not first then
    if flowing and not st.last_flowing then
      flogic_fire(FLOGIC_EV_FLOW_STARTED)
    elseif st.last_flowing and not flowing then
      flogic_fire(FLOGIC_EV_FLOW_STOPPED)
    end
    if water_off and not st.last_water_off then
      flogic_fire(FLOGIC_EV_WATER_OFF)
    elseif st.last_water_off and not water_off then
      flogic_fire(FLOGIC_EV_WATER_OFF_CLEAR)
    end
    if warning and not st.last_warning then
      flogic_fire(FLOGIC_EV_WARNING)
    elseif st.last_warning and not warning then
      flogic_fire(FLOGIC_EV_WARNING_CLEAR)
    end
    if critical and not st.last_critical then
      flogic_fire(FLOGIC_EV_CRITICAL)
    elseif st.last_critical and not critical then
      flogic_fire(FLOGIC_EV_CRITICAL_CLEAR)
    end
    if advance and not st.last_advance then
      flogic_fire(FLOGIC_EV_ADVANCE)
    end
    if mode ~= st.last_mode then
      flogic_fire(FLOGIC_EV_MODE_CHANGED)
    end
  end
  st.last_mode, st.last_flowing = mode, flowing
  st.last_water_off, st.last_warning = water_off, warning
  st.last_critical, st.last_advance = critical, advance
end

local function flogic_sync_tick_timer()
  local st = flogic_state
  local snap = st.last_snapshot
  local flowing = snap ~= nil and FloModel.is_water_flowing(snap.valve)
  if flowing and st.tick_timer == nil then
    st.tick_timer = C4:SetTimer(FLOGIC_LOCAL_TICK_MS, function()
      local current = flogic_state.last_snapshot
      if current == nil or not FloModel.is_water_flowing(current.valve) then
        if flogic_state.tick_timer ~= nil then
          flogic_state.tick_timer:Cancel()
          flogic_state.tick_timer = nil
        end
        return
      end
      local now = os.time()
      flogic_set_prop("Shutoff Countdown", flogic_num(FloModel.shutoff_countdown_seconds(current.valve, now)))
      flogic_set_prop("Flow Elapsed", flogic_num(FloModel.flow_elapsed_seconds(current.valve, now)))
      if FloModel.advance_shutoff_warning(current.valve, current.access, now)
        and not flogic_state.last_advance
      then
        flogic_state.last_advance = true
        flogic_fire(FLOGIC_EV_ADVANCE)
      end
    end, true)
  elseif not flowing and st.tick_timer ~= nil then
    st.tick_timer:Cancel()
    st.tick_timer = nil
  end
end

local function flogic_on_snapshot(snap, session)
  local st = flogic_state
  st.last_snapshot = snap
  if session.relog_token ~= nil
    and session.relog_token ~= ""
    and session.relog_token ~= st.relog_token
  then
    st.relog_token = session.relog_token
    C4:PersistSetValue("flologic_relog", session.relog_token, true)
  end
  flogic_set_connection(true)
  flogic_update_picker(snap.devices)
  flogic_update_properties(snap)
  flogic_process_edges(snap)
  flogic_sync_tick_timer()
end

local function flogic_on_session_error(where, err)
  flogic_log_warn(where .. " failed: " .. tostring(err))
  flogic_set_connection(false, flogic_describe_error(err))
end

-- --- Poll and command engines (one session at a time) ----------------------

local function flogic_run_next()
  local st = flogic_state
  if st.busy then
    return
  end
  local job = table.remove(st.command_queue, 1)
  if job == nil then
    return
  end
  st.busy = true
  local session = flogic_new_session()
  session.send_command(flogic_hub_url(), flogic_selection(), job.fields, function(err)
    st.busy = false
    if err ~= nil then
      flogic_on_session_error("command " .. job.name, err)
    else
      flogic_log("command " .. job.name .. " ok; refreshing")
      flogic_set_connection(true)
      flogic_poll_soon(5000)
    end
    flogic_run_next()
  end)
end

function flogic_poll_soon(delay_ms)
  C4:SetTimer(delay_ms or 1000, function(t)
    t:Cancel()
    flogic_poll_now()
  end, false)
end

function flogic_poll_now()
  local st = flogic_state
  if st.busy then
    flogic_log("poll skipped: session busy")
    return
  end
  if flogic_prop(FLOGIC_PROP_EMAIL) == "" or flogic_prop(FLOGIC_PROP_PASSWORD) == "" then
    flogic_set_prop(FLOGIC_PROP_CONNECTION, "Not configured")
    return
  end
  if st.sha1_digest == nil then
    flogic_set_connection(false, "no SHA1 digest available")
    return
  end
  st.busy = true
  local session = flogic_new_session()
  session.fetch_snapshot(flogic_hub_url(), flogic_selection(), function(err, snap)
    st.busy = false
    if err ~= nil then
      flogic_on_session_error("poll", err)
    else
      flogic_on_snapshot(snap, session)
    end
    flogic_run_next()
  end)
end

local function flogic_poll_interval_ms()
  local seconds = tonumber(flogic_prop(FLOGIC_PROP_POLL)) or 60
  if seconds < FLOGIC_MIN_POLL_SECONDS then
    seconds = FLOGIC_MIN_POLL_SECONDS
  elseif seconds > FLOGIC_MAX_POLL_SECONDS then
    seconds = FLOGIC_MAX_POLL_SECONDS
  end
  return seconds * 1000
end

local function flogic_restart_poll_timer()
  local st = flogic_state
  if st.poll_timer ~= nil then
    st.poll_timer:Cancel()
    st.poll_timer = nil
  end
  st.poll_timer = C4:SetTimer(flogic_poll_interval_ms(), function()
    flogic_poll_now()
  end, true)
end

-- --- Commands (programming) -------------------------------------------------

local function flogic_queue_command(name, fields)
  local st = flogic_state
  if #st.command_queue >= 8 then
    table.remove(st.command_queue, 1)
  end
  st.command_queue[#st.command_queue + 1] = { name = name, fields = fields }
  flogic_run_next()
end

local function flogic_param_number(params, name, minimum, maximum)
  local raw = params ~= nil and params[name] or nil
  local value = tonumber(raw)
  if value == nil or value < minimum or value > maximum then
    return nil
  end
  return value
end

function ExecuteCommand(strCommand, tParams)
  flogic_log("command: " .. tostring(strCommand))
  if strCommand == "Refresh" then
    flogic_poll_now()
    return
  elseif strCommand == "Refresh Valve List" then
    flogic_poll_now() -- picker refreshes from every snapshot
    return
  end
  local mode_commands = {
    ["Set Mode Home"] = "home", ["Set Mode Away"] = "away",
    ["Set Mode Bypass"] = "bypass", ["Set Mode Shutoff"] = "shutoff",
    ["Set Mode Disabled"] = "disabled",
  }
  local mode = mode_commands[strCommand]
  if mode ~= nil then
    flogic_queue_command(strCommand, { mode = FloModel.VALVE_MODES[mode] })
    return
  end
  local value_commands = {
    ["Set Home Limit"] = { param = "Minutes", field = "homeIntervalTime", min = 1, max = 10080 },
    ["Set Away Limit"] = { param = "Minutes", field = "awayIntervalTime", min = 0, max = 10080 },
    ["Set Bypass Time"] = { param = "Minutes", field = "bypassTime", min = 1, max = 10080 },
    ["Set Auto Away"] = { param = "Hours", field = "autoAwayTime", min = 1, max = 8760 },
    ["Set Temp Alert"] = { param = "Temperature", field = "lowTemperatureAlert", min = -50, max = 150 },
    ["Set Temp Shutoff"] = { param = "Temperature", field = "lowTemperatureLimit", min = -50, max = 150 },
    ["Set Pre-Alert"] = { param = "Minutes", field = "preAlertNoticeInterval", min = 1, max = 10080 },
    ["Set No-Flow Notice"] = { param = "Seconds", field = "noFlowNoticeInterval", min = 1, max = 604800 },
    ["Set Flow Sensitivity"] = { param = "Value", field = "dripRate", min = 0, max = 1000 },
  }
  local spec = value_commands[strCommand]
  if spec == nil then
    flogic_log_warn("unknown command: " .. tostring(strCommand))
    return
  end
  local value = flogic_param_number(tParams, spec.param, spec.min, spec.max)
  if value == nil then
    flogic_log_warn("command " .. strCommand .. " rejected: bad " .. spec.param)
    return
  end
  flogic_queue_command(strCommand, { [spec.field] = value })
end

-- --- Lifecycle --------------------------------------------------------------

function OnDriverInit()
  -- Only persist reads are safe here; everything else waits for LateInit.
  local saved = C4:PersistGetValue("flologic_relog")
  if type(saved) == "string" then
    flogic_state.relog_token = saved
  end
end

function OnDriverLateInit()
  math.randomseed(os.time() + (os.clock() * 1000000))
  flogic_state.sha1_digest = flogic_probe_sha1()
  if flogic_state.sha1_digest == nil then
    flogic_set_prop(FLOGIC_PROP_CONNECTION, "Offline: no SHA1 digest available")
    flogic_log_warn("no working SHA1 digest; websocket handshake impossible")
    return
  end
  flogic_restart_poll_timer()
  flogic_poll_soon(2000)
end

function OnDriverDestroyed()
  local st = flogic_state
  if st.poll_timer ~= nil then
    st.poll_timer:Cancel()
  end
  if st.tick_timer ~= nil then
    st.tick_timer:Cancel()
  end
  st.command_queue = {}
end

function OnPropertyChanged(strProperty)
  flogic_log("property changed: " .. tostring(strProperty))
  if strProperty == FLOGIC_PROP_POLL then
    flogic_restart_poll_timer()
  elseif strProperty == FLOGIC_PROP_EMAIL
    or strProperty == FLOGIC_PROP_PASSWORD
    or strProperty == FLOGIC_PROP_HUB
    or strProperty == FLOGIC_PROP_PICKER
    or strProperty == FLOGIC_PROP_OVERRIDE
  then
    flogic_poll_soon(1000)
  end
end

