#!/bin/sh
# Bundle the valve driver for Composer Pro: the shared pure-logic modules
# (model + updater + link protocol, read-only) plus the hand-written
# c4/valve/valve.lua, concatenated into the single driver.lua that ships
# in flologic_valve.c4z. Usage: sh c4/valve/bundle.sh
set -eu
cd "$(dirname "$0")"
{
  echo "-- ============================================================================"
  echo "-- THIS FILE IS GENERATED by valve/bundle.sh. DO NOT EDIT."
  echo "-- ============================================================================"
  echo ""
  # shellcheck disable=SC2043
  for f in ../src/json.lua ../src/model.lua ../src/update.lua ../shared/flologic_link.lua valve.lua; do
    echo "-- ============================================================================"
    echo "-- bundled: $f"
    echo "-- ============================================================================"
    cat "$f"
    echo ""
  done
} > driver.lua
echo "wrote driver.lua ($(wc -l < driver.lua) lines)"
