#!/bin/sh
# Bundle the cloud driver for Composer Pro: the shared protocol stack
# (c4/src/*.lua, read-only) plus the shared link protocol plus the
# hand-written c4/cloud/cloud.lua, concatenated into the single driver.lua
# that ships in flologic_cloud.c4z. Usage: sh c4/cloud/bundle.sh
set -eu
cd "$(dirname "$0")"
{
  echo "-- ============================================================================"
  echo "-- THIS FILE IS GENERATED by cloud/bundle.sh. DO NOT EDIT."
  echo "-- ============================================================================"
  echo ""
  # shellcheck disable=SC2043
  for f in ../src/json.lua ../src/model.lua ../src/signalr.lua ../src/websocket.lua ../src/flologic.lua ../src/update.lua ../shared/flologic_link.lua cloud.lua; do
    echo "-- ============================================================================"
    echo "-- bundled: $f"
    echo "-- ============================================================================"
    cat "$f"
    echo ""
  done
} > driver.lua
echo "wrote driver.lua ($(wc -l < driver.lua) lines)"
