#!/bin/sh
# Bundle c4/src/*.lua into the single driver.lua that ships in the .c4z.
# Every src file is concatenation-safe: it defines globals only, with no
# require/return/top-level execution. Usage: sh c4/scripts/bundle.sh
set -eu
cd "$(dirname "$0")/.."
{
  echo "-- ============================================================================"
  echo "-- THIS FILE IS GENERATED by scripts/bundle.sh from src/*.lua. DO NOT EDIT."
  echo "-- ============================================================================"
  echo ""
  for f in src/bootstrap.lua src/json.lua src/model.lua src/signalr.lua src/websocket.lua src/flologic.lua src/update.lua src/main.lua; do
    echo "-- ============================================================================"
    echo "-- bundled: $f"
    echo "-- ============================================================================"
    cat "$f"
    echo ""
  done
} > driver.lua
echo "wrote driver.lua ($(wc -l < driver.lua) lines)"
